# Generated by Django 5.0.6 on 2026-09-19 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='المُعرّف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='جلباب', max_length=200, verbose_name='العنوان الرئيسي')),
                ('subtitle', models.CharField(default='أناقة إسلامية بلمسة عصرية', max_length=300, verbose_name='الوصف القصير')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='صورة الـ Hero')),
                ('button_text', models.CharField(default='تسوق الآن', max_length=50, verbose_name='نص زر التسوق')),
                ('button_url', models.CharField(default='/products/', help_text='مثال: /products/ أو /products/nqab/', max_length=200, verbose_name='رابط الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّلة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'صورة رئيسية (Hero)',
                'verbose_name_plural': 'الصور الرئيسية (Hero)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة / المنطقة')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الطلب (جنيه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='المُعرّف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الحالي (جنيه)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='اتركه فارغًا إذا لم يكن هناك خصم.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر قبل الخصم (جنيه)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='المخزون')),
                ('is_new', models.BooleanField(default=False, verbose_name='منتج جديد؟')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='عليه خصم؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّل للعرض؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج وقت الطلب')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر وقت الطلب')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='store_produ_created_0fbdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
    ]
